# This file was generated by tools/update/update.py

require sispmctl.inc

# Version 4.12 released 2024-05-04 17:00:49
SRC_URI[md5sum] = "3a4575e46602fe44bd57075c143cdc3b"
SRC_URI[sha256sum] = "e757863a4838da6e1ca72a57adc5aca6fc47ffbddc72a69052d8abd743d57082"
