# This file was generated by tools/update/update.py

require python3-labgrid.inc

# Version v25.0-111-ge9e43aa commited 2025-09-13 12:47:10 +0200
PV = "25.0+git"
SRCBRANCH = "master"
SRCREV = "e9e43aac6c135f4e105e29ad5bdfa46ab2e9ec8e"

LABGRID_USE_DEVEL_VERSION[doc] = "Global switch to enable labgrid development (git) version"
LABGRID_USE_DEVEL_VERSION ??= "-1"
DEFAULT_PREFERENCE ??= "${LABGRID_USE_DEVEL_VERSION}"
