# This file was generated by tools/update/update.py

require python3-aiohttp-json-rpc.inc

# Version 0.13.3 released 2020-12-14T10:13:07.
SRC_URI[sha256sum] = "6237a104478c22c6ef96c7227a01d6832597b414e4b79a52d85593356a169e99"
