# This file was generated by tools/update/update.py

require python3-powerrelay.inc

# Commit 41c030f09495f67e5573b6f0d7411fef71d92e9e created 2023-06-07 13:20:13 +0200
SRCBRANCH = "master"
SRCREV = "41c030f09495f67e5573b6f0d7411fef71d92e9e"
