# This file was generated by tools/update/update.py

require python3-grpcio-channelz.inc

# Version 1.74.0 released 2025-07-24T19:02:00.
SRC_URI[sha256sum] = "6b80079b6d6e3484eaf89f4e547438e8fcb8658f244027dafb67803bbbd07d4b"
