# This file was generated by tools/update/update.py

require python3-janus.inc

# Version 2.0.0 released 2024-12-13T12:59:08.
SRC_URI[sha256sum] = "0970f38e0e725400496c834a368a67ee551dc3b5ad0a257e132f5b46f2e77770"
