# This file was generated by tools/update/update.py

require python3-usbmuxctl.inc

# Version 0.1.4 released 2024-04-26T07:52:01.
SRC_URI[sha256sum] = "f200647bd72ea5b5a77d6d9e1f0641e2aae1da37fc2317a2f73929b034388845"
