# This file was generated by tools/update/update.py

require python3-labgrid.inc

# Git tag v25.0.1 pointing at a commit from 2025-07-07 18:57:46 +0200
SRCBRANCH = "stable-25.0"
SRCREV = "4b2f81389386454a0eb84e361e776ea818ffb038"
