# This file was generated by tools/update/update.py

require python3-usbsdmux.inc

# Git tag 25.08 pointing at a commit from 2025-08-07 11:47:51 +0200
SRCBRANCH = "master"
SRCREV = "dc8ea0ea05cd1cf02902fbfebf79061389a69097"
