# This file was generated by tools/update/update.py

require python3-grpcio-reflection.inc

# Version 1.74.0 released 2025-07-24T19:01:56.
SRC_URI[sha256sum] = "c7327d2520dcdac209872ebf57774c3239646dad882e4abb4ad7bebccaca2c83"
