# This file was generated by tools/update/update.py

require python3-pyserial.inc

# Version 3.4.0.1 released 2018-09-10T14:15:27Z.
SRC_URI += "https://github.com/labgrid-project/pyserial/releases/download/v3.4.0.1/pyserial_v3.4.0.1.tar.gz"
SRC_URI[sha256sum] = "72bdb6863c4e12047e14be037f6b30e24901aa98af8ac7b63d6aab170db5790e"
