# This file was generated by tools/update/update.py

require python3-lxa-iobus.inc

# Git tag v0.5.1 pointing at a commit from 2024-04-15 08:19:08 +0200
SRCBRANCH = "master"
SRCREV = "1d90a81eef5a61fd0d2bfdcd72a7a1e98cbf1290"
